package net.novateam.nvt_mod;

import org.quiltmc.loader.api.ModContainer;

import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraft.item.Item.Settings;
import net.minecraft.item.ItemGroups;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.util.Identifier;

public class PlantsItems {
    public static final Item BELLADONNA_ITEM = new Item(new Settings());
    public static final Block BELLADONNA_BLOCK = new Block(new Settings());
    public static final Item HEMLOCK_ITEM = new Item(new Settings());
    public static final Item BROADLEAF_PLANTAIN_ITEM = new Item(new Settings());
    public static final Item POPPY_ITEM = new Item(new Settings());
    public static final Item PUREFLOWER_ITEM = new Item(new Settings());
    public static final Item FROZEN_BOAT_ITEM = new Item(new Settings());
    public static final Item DEMON_EYE_ITEM = new Item(new Settings());
    public static final Item MINER_PAIN_ITEM = new Item(new Settings());
    public static final Item VERTICE_MONTIS_ITEM = new Item(new Settings());
    public static final Item PRAIRY_SUN_ITEM = new Item(new Settings());
    public static final Item NOX_DIRA_ITEM = new Item(new Settings());
    public static final Item NOX_PLACIDA_ITEM = new Item(new Settings());
    public static final Item ABYSSAL_STARE_ITEM = new Item(new Settings());
    public static final Item HAG_HAIR_ITEM = new Item(new Settings());
    public static final Item COGFLOWER_ITEM = new Item(new Settings());
    public static final Item MUMMY_TOE_ITEM = new Item(new Settings());
    public static final Item IMP_TONGUE_ITEM = new Item(new Settings());
    public static final Item WISHFULL_STAR_ITEM = new Item(new Settings());
    public static final Item ANCHORWEED_ITEM = new Item(new Settings());
    public static final Item SNOWCHILD_ITEM = new Item(new Settings());
    public static final Item TALLFLOWER_ITEM = new Item(new Settings());
    public static final Item SADGUY_ITEM = new Item(new Settings());
    public static final Item ANCIENT_BAMBOO_FRUIT_ITEM = new Item(new Settings());
    public static final Item DRYFLOWER_ITEM = new Item(new Settings());
    public static final Item SLITHERGRASS_ITEM = new Item(new Settings());
    public static final Item FALLENFLOWER_ITEM = new Item(new Settings());
    public static void register(ModContainer mod) {
        Registry.register(Registries.ITEM, new Identifier(mod.metadata().id(), "belladonna"), BELLADONNA_ITEM);
        Registry.register(Registries.BLOCK, new Identifier(mod.metadata().id(), "belladonna"), BELLADONNA_BLOCK);
        Registry.register(Registries.ITEM, new Identifier(mod.metadata().id(), "hemlock"), HEMLOCK_ITEM);
        Registry.register(Registries.ITEM, new Identifier(mod.metadata().id(), "broadleaf_plantain"), BROADLEAF_PLANTAIN_ITEM);
        Registry.register(Registries.ITEM, new Identifier(mod.metadata().id(), "poppy"), POPPY_ITEM);
        Registry.register(Registries.ITEM, new Identifier(mod.metadata().id(), "pureflower"), PUREFLOWER_ITEM);
        Registry.register(Registries.ITEM, new Identifier(mod.metadata().id(), "frozen_boat"), FROZEN_BOAT_ITEM);
        Registry.register(Registries.ITEM, new Identifier(mod.metadata().id(), "demon_eye"), DEMON_EYE_ITEM);
        Registry.register(Registries.ITEM, new Identifier(mod.metadata().id(), "miner_pain"), MINER_PAIN_ITEM);
        Registry.register(Registries.ITEM, new Identifier(mod.metadata().id(), "vertice_montis"), VERTICE_MONTIS_ITEM);
        Registry.register(Registries.ITEM, new Identifier(mod.metadata().id(), "prairy_sun"), PRAIRY_SUN_ITEM);
        Registry.register(Registries.ITEM, new Identifier(mod.metadata().id(), "nox_dira"), NOX_DIRA_ITEM);
        Registry.register(Registries.ITEM, new Identifier(mod.metadata().id(), "nox_placida"), NOX_PLACIDA_ITEM);
        Registry.register(Registries.ITEM, new Identifier(mod.metadata().id(), "abyssal_stare"), ABYSSAL_STARE_ITEM);
        Registry.register(Registries.ITEM, new Identifier(mod.metadata().id(), "hag_hair"), HAG_HAIR_ITEM);
        Registry.register(Registries.ITEM, new Identifier(mod.metadata().id(), "cogflower"), COGFLOWER_ITEM);
        Registry.register(Registries.ITEM, new Identifier(mod.metadata().id(), "mummy_toe"), MUMMY_TOE_ITEM);
        Registry.register(Registries.ITEM, new Identifier(mod.metadata().id(), "imp_tongue"), IMP_TONGUE_ITEM);
        Registry.register(Registries.ITEM, new Identifier(mod.metadata().id(), "wishfull_star"), WISHFULL_STAR_ITEM);
        Registry.register(Registries.ITEM, new Identifier(mod.metadata().id(), "anchorweed"), ANCHORWEED_ITEM);
        Registry.register(Registries.ITEM, new Identifier(mod.metadata().id(), "snowchild"), SNOWCHILD_ITEM);
        Registry.register(Registries.ITEM, new Identifier(mod.metadata().id(), "tallflower"), TALLFLOWER_ITEM);
        Registry.register(Registries.ITEM, new Identifier(mod.metadata().id(), "sadguy"), SADGUY_ITEM);
        Registry.register(Registries.ITEM, new Identifier(mod.metadata().id(), "ancient_bamboo_fruit"), ANCIENT_BAMBOO_FRUIT_ITEM);
        Registry.register(Registries.ITEM, new Identifier(mod.metadata().id(), "dryflower"), DRYFLOWER_ITEM);
        Registry.register(Registries.ITEM, new Identifier(mod.metadata().id(), "slithergrass"), SLITHERGRASS_ITEM);
        Registry.register(Registries.ITEM, new Identifier(mod.metadata().id(), "fallenflower"), FALLENFLOWER_ITEM);
        ItemGroupEvents.modifyEntriesEvent(ItemGroups.NATURAL_BLOCKS).register(entries -> {
            entries.addItem(BELLADONNA_ITEM);
            entries.addItem(HEMLOCK_ITEM);
            entries.addItem(BROADLEAF_PLANTAIN_ITEM);
            entries.addItem(POPPY_ITEM);
            entries.addItem(PUREFLOWER_ITEM);
            entries.addItem(FROZEN_BOAT_ITEM);
            entries.addItem(DEMON_EYE_ITEM);
            entries.addItem(MINER_PAIN_ITEM);
            entries.addItem(VERTICE_MONTIS_ITEM);
            entries.addItem(PRAIRY_SUN_ITEM);
            entries.addItem(NOX_DIRA_ITEM);
            entries.addItem(NOX_PLACIDA_ITEM);
            entries.addItem(ABYSSAL_STARE_ITEM);
            entries.addItem(HAG_HAIR_ITEM);
            entries.addItem(COGFLOWER_ITEM);
            entries.addItem(MUMMY_TOE_ITEM);
            entries.addItem(IMP_TONGUE_ITEM);
            entries.addItem(WISHFULL_STAR_ITEM);
            entries.addItem(ANCHORWEED_ITEM);
            entries.addItem(SNOWCHILD_ITEM);
            entries.addItem(TALLFLOWER_ITEM);
            entries.addItem(SADGUY_ITEM);
            entries.addItem(ANCIENT_BAMBOO_FRUIT_ITEM);
            entries.addItem(DRYFLOWER_ITEM);
            entries.addItem(SLITHERGRASS_ITEM);
            entries.addItem(FALLENFLOWER_ITEM);
        });
    }
}
